Backport: close button instead of go to home when in widget mode (#3087)
* Merge pull request #3058 from element-hq/valere/refactor_error_handling

refactor: Centralize group call errors in custom GroupCallErrorBoundary

* Merge pull request #3063 from element-hq/valere/fix_add_close_button_in_widget_mode

Error: use a close button instead of go to home when in widget mode